-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 11:18:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- (Pablo) Añadido y conecta a la base de datos
ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema swdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `swdb`;

-- -----------------------------------------------------
-- Table `swdb`.`data_sessions`
-- -----------------------------------------------------
  ----------------------------------------------------
--  `emg_muscle_activity_s1` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s1` INT NULL DEFAULT NULL,
--  `emg_muscle_activity_s2` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s2` FLOAT NULL DEFAULT NULL,
--  `emg_muscle_activity_s3` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s3` FLOAT NULL DEFAULT NULL,
--  `emg_muscle_activity_s4` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s4` FLOAT NULL DEFAULT NULL,
--  `emg_muscle_activity_s5` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s5` FLOAT NULL DEFAULT NULL,
--  `emg_muscle_activity_s6` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s6` FLOAT NULL DEFAULT NULL,
--  `emg_muscle_activity_s7` FLOAT NULL DEFAULT NULL,
--  `muscle_binary_activation_s7` FLOAT NULL DEFAULT NULL,
-- `emg_muscle_activity_s8` FLOAT NULL DEFAULT NULL,
-- `muscle_binary_activation_s8` FLOAT NULL DEFAULT NULL,
  --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `swdb`.`data_sessions` (
  `iddata_sessions` INT NOT NULL AUTO_INCREMENT,
  `idSesion` INT NULL DEFAULT NULL,
  `Date` BIGINT NULL DEFAULT NULL,
  `left_hip` FLOAT NULL DEFAULT NULL,
  `right_hip` FLOAT NULL DEFAULT NULL,
  `weight_gauge` FLOAT NULL DEFAULT NULL,
  `direction` VARCHAR(45) NULL DEFAULT NULL,
  `accX_s7` FLOAT NULL DEFAULT NULL,
  `accX_s3` FLOAT NULL DEFAULT NULL,
   PRIMARY KEY (`iddata_sessions`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `swwdb`.`tabla_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swdb`.`tabla_pacientes` (
  `idtabla_pacientes` INT NOT NULL AUTO_INCREMENT,
  `NombrePaciente` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoPaciente` VARCHAR(45) NULL DEFAULT NULL,
  `patiente_age` VARCHAR(45) NULL DEFAULT NULL,
  `patient_gender` VARCHAR(45) NULL DEFAULT NULL,
  `patient_active_rom` VARCHAR(45) NULL DEFAULT NULL,
  `patiente_weight` VARCHAR(45) NULL DEFAULT NULL,
  `patient_height` VARCHAR(45) NULL DEFAULT NULL,
  `leg_length` VARCHAR(45) NULL DEFAULT NULL,
  `estado_fisico` VARCHAR(45) NULL DEFAULT NULL,
  `estado_cognitivo` VARCHAR(45) NULL DEFAULT NULL,
  `surgery` VARCHAR(45) NULL DEFAULT NULL,
  `hip_joint`  VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtabla_pacientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `swdb`.`tabla_sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swdb`.`tabla_sesion` (
  `idtable_session` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idPaciente` INT NULL DEFAULT NULL,
  `idTerapeuta` INT NULL DEFAULT NULL,
  `NumberSession` INT NULL DEFAULT NULL,
  `gait_velocity` VARCHAR(45) NULL DEFAULT NULL,
  `observations` VARCHAR(500) NULL DEFAULT NULL,

  PRIMARY KEY (`idtable_session`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `swdb`.`tabla_terapeutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swdb`.`tabla_terapeutas` (
  `idtabla_terapeutas` INT NOT NULL AUTO_INCREMENT,
  `NombreTerapeuta` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoTerapeuta` VARCHAR(45) NULL DEFAULT NULL,
  `Centro` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtabla_terapeutas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
